name: Resume

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Resume
      run: make
      
    - name: Publish Resume
      uses: actions/upload-artifact@v3
      with:
        name: resume
        path: ./build/resume.pdf
